const { Product } = require("../models");

const gearData = [
  {
    product_name: "Acid, Flask of",
    description:
      "You can throw a flask of acid as a splash weapon. Treat this attack as a ranged touch attack with a range increment of 10 feet. A direct hit deals 1d6 points of acid damage. Every creature within 5 feet of the point where the acid hits takes 1 point of acid damage from the splash.",
    cost: 10,
    stock: 7,
    weight: 1,
    image_link: "/img/magic_potion.png",
    image_alt_text: "Potion Magic",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Alchemical Sleep Gas",
    description: "DC 17 or sleep for 1 round; DC 15 or sleep for d4+1 min.",
    cost: 30,
    stock: 11,
    weight: 1,
    image_link: "/img/sleepGas.png",
    image_alt_text: "Sleep Gas",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Alchemist's Fire, Flask of",
    description:
      "You can throw a flask of alchemist's fire as a splash weapon. Treat this attack as a ranged touch attack with a range increment of 10 feet.\n\nA direct hit deals 1d6 points of fire damage. Every creature within 5 feet of the point where the flask hits takes 1 point of fire damage from the splash. On the round following a direct hit, the target takes an additional 1d6 points of damage. If desired, the target can use a full-round action to attempt to extinguish the flames before taking this additional damage. Extinguishing the flames requires a DC 15 Reflex save. Rolling on the ground provides the target a +2 bonus on the save. Leaping into a lake or magically extinguishing the flames automatically smothers the fire.",
    cost: 20,
    stock: 10,
    weight: 1,
    image_link: "/img/magic_potion.png",
    image_alt_text: "Potion Magic",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Alchemists' Lab",
    description:
      "An alchemist's lab always has the perfect tool for making alchemical items, so it provides a +2 circumstance bonus on Craft (alchemy) checks. It has no bearing on the costs related to the Craft (alchemy) skill. Without this lab, a character with the Craft (alchemy) skill is assumed to have enough tools to use the skill but not enough to get the +2 bonus that the lab provides.",
    cost: 500,
    stock: 12,
    weight: 40,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Altar Case, Granite",
    description: "traveling altar.",
    cost: 40,
    stock: 10,
    weight: 40,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Case, Spruce",
    description: "traveling altar.",
    cost: 20,
    stock: 2,
    weight: 5,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Cloth, Gold Brocade",
    cost: 40,
    stock: 15,
    weight: 0,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Cloth, Linen",
    cost: 15,
    stock: 15,
    weight: 0,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Cloth, Silk",
    cost: 35,
    stock: 2,
    weight: 0,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Cloth, Small",
    cost: 3,
    stock: 0,
    weight: 0,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Altar Cloth, Velvet",
    cost: 30,
    stock: 11,
    weight: 0,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Amulet",
    description: "(Typically a magical item)",
    cost: 0,
    stock: 16,
    weight: 0,
    image_link: "/img/amulet.png",
    image_alt_text: "Amulet",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Animal Feed",
    cost: 0.05,
    stock: 19,
    weight: 10,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Antitoxin",
    description:
      "If you drink antitoxin, you get a +5 alchemical bonus on Fortitude saving throws against poison for 1 hour.",
    cost: 50,
    stock: 2,
    weight: 0.1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Arcane Lab",
    cost: 500,
    stock: 7,
    weight: 40,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Arcane Library",
    description: "At least 200 rare volumes",
    cost: 10000,
    stock: 12,
    weight: 600,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Artisan's Outfit",
    description:
      "This outfit includes a shirt with buttons, a skirt or pants with a drawstring, shoes, and perhaps a cap or hat. It may also include a belt or a leather or cloth apron for carrying tools.",
    cost: 1,
    stock: 18,
    weight: 4,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Artisan's Tools",
    description:
      "These special tools include the items needed to pursue any craft. Without them, you have to use improvised tools (-2 penalty on Craft checks), if you can do the job at all.",
    cost: 5,
    stock: 7,
    weight: 5,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Artisan's Tools, Masterwork",
    description:
      "These tools serve the same purpose as artisan's tools (above), but masterwork artisan's tools are the perfect tools for the job, so you get a +2 circumstance bonus on Craft checks made with them.",
    cost: 55,
    stock: 13,
    weight: 5,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Aspergillum, Gold",
    description: "Holds 3 flasks holy water; Std Act. range touch attack",
    cost: 45,
    stock: 13,
    weight: 3,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Aspergillum, Iron",
    description: "Holds 3 flasks holy water; Std Act. range touch attack",
    cost: 5,
    stock: 2,
    weight: 3,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Aspergillum, Silver (DotF)",
    description: "Holds 3 flasks holy water; Std Act. range touch attack",
    cost: 20,
    stock: 9,
    weight: 3,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Aspergillum, Silver (FRCS)",
    description: "Holds 3 flasks holy water; Std Act. range touch attack",
    cost: 50,
    stock: 1,
    weight: 3,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Backpack",
    description: "Holds 1 cu. ft",
    cost: 2,
    stock: 14,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Bandoleer",
    description: "Carries up to 8 small items.",
    cost: 0.5,
    stock: 5,
    weight: 0.5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Bandoleer, Masterwork",
    description: "Carries up to 12 small items.",
    cost: 5,
    stock: 17,
    weight: 0.5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Barrel",
    description: "Holds 10 cu ft",
    cost: 2,
    stock: 1,
    weight: 30,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Basket",
    description: "Holds 2 cu ft",
    cost: 0.4,
    stock: 4,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Bedroll",
    cost: 0.1,
    stock: 15,
    weight: 5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Bell",
    cost: 1,
    stock: 1,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Bellows Mask",
    cost: -1,
    stock: 11,
    weight: 3,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Belt",
    cost: 0,
    stock: 18,
    weight: 1,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Bit and Bridle",
    cost: 2,
    stock: 5,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Blanket, Winter",
    cost: 0.5,
    stock: 18,
    weight: 3,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Block & Tackle",
    cost: 5,
    stock: 8,
    weight: 5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Book",
    cost: 15,
    stock: 6,
    weight: 3,
    image_link: "/img/scroll.png",
    image_alt_text: "Scroll",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Boot Pumps",
    cost: -1,
    stock: 19,
    weight: 20,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Bottle, Wine, Glass",
    cost: 2,
    stock: 15,
    weight: 0,
    image_link: "/img/wineglass.png",
    image_alt_text: "Wineglass",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Bracers",
    cost: 0,
    stock: 18,
    weight: 1,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Field, Bronze",
    cost: 4,
    stock: 13,
    weight: 5,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Field, Silver",
    cost: 15,
    stock: 18,
    weight: 6,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Large, Bronze",
    cost: 30,
    stock: 15,
    weight: 75,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Large, Gold",
    cost: 110,
    stock: 4,
    weight: 160,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Large, Silver",
    cost: 70,
    stock: 6,
    weight: 80,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Medium, Bronze",
    cost: 17,
    stock: 1,
    weight: 25,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Medium, Gold",
    cost: 70,
    stock: 0,
    weight: 60,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Brazier, Medium, Silver",
    cost: 30,
    stock: 6,
    weight: 30,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Bucket",
    description: "Holds 1 cu ft",
    cost: 0.5,
    stock: 13,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Caltrops",
    description:
      "A caltrop is a four-pronged iron spike crafted so that one prong faces up no matter how the caltrop comes to rest. You scatter caltrops on the ground in the hope that your enemies step on them or are at least forced to slow down to avoid them. One 2- pound bag of caltrops covers an area 5 feet square.\n\nEach time a creature moves into an area covered by caltrops (or spends a round fighting while standing in such an area), it might step on one. The caltrops make an attack roll (base attack bonus +0) against the creature. For this attack, the creature's shield, armor, and deflection bonuses do not count. If the creature is wearing shoes or other footwear, it gets a +2 armor bonus to AC. If the caltrops succeed on the attack, the creature has stepped on one. The caltrop deals 1 point of damage, and the creature's speed is reduced by one-half because its foot is wounded. This movement penalty lasts for 24 hours, or until the creature is successfully treated with a DC 15 Heal check, or until it receives at least 1 point of magical curing. A charging or running creature must immediately stop if it steps on a caltrop. Any creature moving at half speed or slower can pick its way through a bed of caltrops with no trouble.\n\nCaltrops may not be effective against unusual opponents.",
    cost: 1,
    stock: 5,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Candelabra, 16-candle, Gold",
    description: "light: 20' radius",
    cost: 45,
    stock: 2,
    weight: 6,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candelabra, 16-candle, Silver",
    description: "light: 20' radius",
    cost: 25,
    stock: 7,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candelabra, 8-candle, Gold",
    description: "light: 15' radius",
    cost: 35,
    stock: 9,
    weight: 2,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candelabra, 8-candle, Silver",
    description: "light: 15' radius",
    cost: 20,
    stock: 6,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candle",
    description:
      "A candle dimly illuminates a 5-foot radius and burns for 1 hour.",
    cost: 0.01,
    stock: 19,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Candle, 12-hour",
    description: "Lights a 15' area for 12 hours",
    cost: 0.5,
    stock: 15,
    weight: 0.25,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candle, Temple (per foot)",
    cost: 1,
    stock: 18,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candle, timekeeping",
    cost: 1,
    stock: 1,
    weight: 0.25,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candle, vigil",
    description: "Burning through night gives a +1 to Heal",
    cost: 10,
    stock: 13,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candlestick, Gold",
    cost: 20,
    stock: 5,
    weight: 2,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candlestick, Hand-Held, Gold",
    cost: 3,
    stock: 1,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candlestick, Hand-Held, Silver",
    cost: 0.5,
    stock: 13,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Candlestick, Silver",
    cost: 12,
    stock: 8,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Canvas (per sq. yd.)",
    cost: 0.1,
    stock: 7,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Carriage",
    description:
      "This four-wheeled vehicle can transport as many as four people within an enclosed cab, plus two drivers. In general, two horses (or other beasts of burden) draw it. A carriage comes with the harness needed to pull it.",
    cost: -1,
    stock: 19,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Cart",
    description:
      "This two-wheeled vehicle can be drawn by a single horse (or other beast of burden). It comes with a harness.",
    cost: 15,
    stock: 6,
    weight: 200,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Case, Map or Scroll",
    cost: 1,
    stock: 1,
    weight: 0.5,
    image_link: "/img/scroll.png",
    image_alt_text: "Scroll",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Castle",
    description: "Keep; 15ft high; 10ft thick stone wall; 4 towers",
    cost: 500000,
    stock: 16,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Censer, Brass",
    cost: 1,
    stock: 4,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Censer, Gold",
    cost: 5,
    stock: 16,
    weight: 4,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Censer, Silver",
    cost: 3,
    stock: 10,
    weight: 2,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Chain (per 10')",
    description:
      "Chain has hardness 10 and 5 hit points. It can be burst with a DC 26 Strength check.",
    cost: 30,
    stock: 13,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Chalk, 1 piece",
    cost: 0.01,
    stock: 2,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Chess Set (Common)",
    cost: 2,
    stock: 19,
    weight: 4,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Chess Set (Fine)",
    cost: 25,
    stock: 13,
    weight: 7,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Chest",
    description: "Holds 2 cu ft",
    cost: 2,
    stock: 14,
    weight: 25,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Cleric's Vestments",
    description:
      "These ecclesiastical clothes are for performing priestly functions, not for adventuring.",
    cost: 5,
    stock: 4,
    weight: 6,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Climber's Kit",
    description:
      "This is the perfect tool for climbing and gives you a +2 circumstance bonus on Climb checks.",
    cost: 80,
    stock: 6,
    weight: 5,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Coins Stored: Copper",
    cost: 0.01,
    stock: 5,
    weight: 0.02,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Coins Stored: Gold",
    cost: 1,
    stock: 13,
    weight: 0.02,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Coins Stored: Platinum",
    cost: 10,
    stock: 3,
    weight: 0.02,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Coins Stored: Silver",
    cost: 0.1,
    stock: 0,
    weight: 0.02,
    image_link: "/img/jewels.png",
    image_alt_text: "Jewels",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Cold Weather Outfit",
    description:
      "A cold weather outfit includes a wool coat, linen shirt, wool cap, heavy cloak, thick pants or skirt, and boots. This outfit grants a +5 circumstance bonus on Fortitude saving throws against exposure to cold weather.",
    cost: 8,
    stock: 16,
    weight: 7,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Courtier's Outfit",
    description:
      "This outfit includes fancy, tailored clothes in whatever fashion happens to be the current style in the courts of the nobles. Anyone trying to influence nobles or courtiers while wearing street dress will have a hard time of it (-2 penalty on Charisma-based skill checks to influence such individuals). If you wear this outfit without jewelry (costing an additional 50 gp), you look like an out-of-place commoner.",
    cost: 30,
    stock: 11,
    weight: 6,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Crowbar",
    description:
      "A crowbar it grants a +2 circumstance bonus on Strength checks made for such purposes. If used in combat, treat a crowbar as a one-handed improvised weapon that deals bludgeoning damage equal to that of a club of its size.",
    cost: 2,
    stock: 3,
    weight: 5,
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Disappearing Ink",
    description: "Fades after 1 hour",
    cost: 5,
    stock: 2,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Disguise Kit",
    description:
      "The kit is the perfect tool for disguise and provides a +2 circumstance bonus on Disguise checks. A disguise kit is exhausted after ten uses.",
    cost: 50,
    stock: 3,
    weight: 8,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Dog, Guard",
    cost: 25,
    stock: 14,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Dog, Riding",
    description:
      "This Medium dog is specially trained to carry a Small humanoid rider. It is brave in combat like a warhorse. You take no damage when you fall from a riding dog.",
    cost: 150,
    stock: 11,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Donkey",
    description:
      "Donkeys and mules are stolid in the face of danger, hardy, surefooted, and capable of carrying heavy loads over vast distances. Unlike a horse, a donkey or a mule is willing (though not eager) to enter dungeons and other strange or threatening places.",
    cost: 8,
    stock: 7,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Draughts set",
    cost: 1,
    stock: 17,
    weight: 2,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Dust",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 3,
    weight: 0,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Entertainer's Outfit",
    description:
      "This set of flashy, perhaps even gaudy, clothes is for entertaining. While the outfit looks whimsical, its practical design lets you tumble, dance, walk a tightrope, or just run (if the audience turns ugly).",
    cost: 3,
    stock: 18,
    weight: 4,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Explorer's Outfit",
    description:
      "This is a full set of clothes for someone who never knows what to expect. It includes sturdy boots, leather breeches or a skirt, a belt, a shirt (perhaps with a vest or jacket), gloves, and a cloak. Rather than a leather skirt, a leather overtunic may be worn over a cloth skirt. The clothes have plenty of pockets (especially the cloak). The outfit also includes any extra items you might need, such as a scarf or a wide-brimmed hat.",
    cost: 1,
    stock: 17,
    weight: 8,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Familiar Carrier (Diminutive)",
    description: "Metal hutch lined w/ wood & padding",
    cost: 15,
    stock: 12,
    weight: 18,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Familiar Carrier (Fine)",
    description: "Metal hutch lined w/ wood & padding",
    cost: 8,
    stock: 15,
    weight: 8,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Familiar Carrier (Medium)",
    description: "Metal hutch lined w/ wood & padding",
    cost: 120,
    stock: 11,
    weight: 200,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Familiar Carrier (Small)",
    description: "Metal hutch lined w/ wood & padding",
    cost: 60,
    stock: 15,
    weight: 90,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Familiar Carrier (Tiny)",
    description: "Metal hutch lined w/ wood & padding",
    cost: 30,
    stock: 0,
    weight: 40,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Firewood (per day)",
    cost: 0.01,
    stock: 12,
    weight: 20,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Fishhook",
    cost: 0.1,
    stock: 8,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Fishing net, 25' sq.",
    cost: 4,
    stock: 13,
    weight: 5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Flash Pellet",
    description: "Reflex DC 15 or dazzled",
    cost: 50,
    stock: 3,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Flask",
    cost: 0.03,
    stock: 3,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Flint & Steel",
    description:
      "Lighting a torch with flint and steel is a full-round action, and lighting any other fire with them takes at least that long.",
    cost: 1,
    stock: 3,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Galley",
    description:
      "This three-masted ship has seventy oars on either side and requires a total crew of 200. A galley is 130 feet long and 20 feet wide, and it can carry 150 tons of cargo or 250 soldiers. For 8,000 gp more, it can be fitted with a ram and castles with firing platforms fore, aft, and amidships. This ship cannot make sea voyages and sticks to the coast. It moves about 4 miles per hour when being rowed or under sail.",
    cost: 30000,
    stock: 6,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Gloves",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 7,
    weight: 0,
    image_link: "/img/gloves.png",
    image_alt_text: "Gloves",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Glow Powder",
    cost: 50,
    stock: 4,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Grand House",
    description: "4 to 10 room wooden house; thatch roof",
    cost: 5000,
    stock: 19,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Grappling Hook",
    description:
      "Throwing a grappling hook successfully requires a Use Rope check (DC 10, +2 per 10 feet of distance thrown).",
    cost: 1,
    stock: 4,
    weight: 4,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Hammer",
    description:
      "If a hammer is used in combat, treat it as a one-handed improvised weapon that deals bludgeoning damage equal to that of a spiked gauntlet of its size.",
    cost: 0.5,
    stock: 5,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Hammock",
    cost: 0.1,
    stock: 18,
    weight: 2,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Headlamp",
    cost: -1,
    stock: 14,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Headlamp Refill",
    cost: -1,
    stock: 12,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Healer's Kit",
    description:
      "It is the perfect tool for healing and provides a +2 circumstance bonus on Heal checks. A healer's kit is exhausted after ten uses.",
    cost: 50,
    stock: 5,
    weight: 1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Healing Salve",
    description: "Full round; heals d8 damage",
    cost: 50,
    stock: 9,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Hemp Rope",
    description: "2 HP; Str DC 23",
    cost: 1,
    stock: 3,
    weight: 10,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Herb: Cassil",
    description: "Makes men infertile for 3d4 days.",
    cost: 1,
    stock: 17,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Herb: Nara Root",
    description: "Makes women infertile for d4+2 days.",
    cost: 0.2,
    stock: 9,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Heward's Handy Haversack",
    cost: 2000,
    stock: 18,
    weight: 5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Holly & Mistletoe",
    cost: 0,
    stock: 12,
    weight: 0,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Holy Symbol, Bronze",
    cost: 10,
    stock: 8,
    weight: 1,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Holy Symbol, Gold",
    cost: 50,
    stock: 9,
    weight: 2,
    image_link: "/img/clericItems.png",
    image_alt_text: "Cleric Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Holy Symbol, Silver",
    description:
      "A holy symbol focuses positive energy. A cleric or paladin uses it as the focus for his spells and as a tool for turning undead. Each religion has its own holy symbol.\n\nUnholy Symbols: An unholy symbol is like a holy symbol except that it focuses negative energy and is used by evil clerics (or by neutral clerics who want to cast evil spells or command undead).",
    cost: 25,
    stock: 18,
    weight: 1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Holy Symbol, Wooden",
    description:
      "A holy symbol focuses positive energy. A cleric or paladin uses it as the focus for his spells and as a tool for turning undead. Each religion has its own holy symbol.\n\nUnholy Symbols: An unholy symbol is like a holy symbol except that it focuses negative energy and is used by evil clerics (or by neutral clerics who want to cast evil spells or command undead).",
    cost: 1,
    stock: 1,
    weight: 0.1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Holy Water, Flask of",
    description:
      "Holy water damages undead creatures and evil outsiders almost as if it were acid. A flask of holy water can be thrown as a splash weapon.\n\nTreat this attack as a ranged touch attack with a range increment of 10 feet. A flask breaks if thrown against the body of a corporeal creature, but to use it against an incorporeal creature, you must open the flask and pour the holy water out onto the target. Thus, you can douse an incorporeal creature with holy water only if you are adjacent to it. Doing so is a ranged touch attack that does not provoke attacks of opportunity.\n\nA direct hit by a flask of holy water deals 2d4 points of damage to an undead creature or an evil outsider. Each such creature within 5 feet of the point where the flask hits takes 1 point of damage from the splash.\n\nTemples to good deities sell holy water at cost (making no profit).",
    cost: 25,
    stock: 0,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Horse, heavy",
    cost: 200,
    stock: 17,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Horse, light",
    cost: 75,
    stock: 14,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Hourglass",
    cost: 25,
    stock: 17,
    weight: 1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Huge Castle",
    description: "Numerous buildings; 20-ft high wall; 6 towers",
    cost: 1000000,
    stock: 6,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Incense, Common (pound)",
    cost: 5,
    stock: 6,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Incense, Exotic (ounce)",
    cost: 15,
    stock: 9,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Ink (1 oz. Vial)",
    description:
      "This is black ink. You can buy ink in other colors, but it costs twice as much.",
    cost: 8,
    stock: 4,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Ink Pen",
    cost: 0.1,
    stock: 6,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Insect Netting",
    description: "Keeps away normal insects.",
    cost: 5,
    stock: 7,
    weight: 1,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Ioun Stone",
    description: "(Typically a magical item)",
    cost: 0,
    stock: 3,
    weight: 0,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Jug, Clay",
    description:
      "This basic ceramic jug is fitted with a stopper and holds 1 gallon of liquid.",
    cost: 0.03,
    stock: 10,
    weight: 9,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Keelboat",
    description:
      "This 50- to 75-foot-long ship is 15 to 20 feet wide and has a few oars to supplement its single mast with a square sail. It has a crew of eight to fifteen and can carry 40 to 50 tons of cargo or 100 soldiers. It can make sea voyages, as well as sail down rivers (thanks to its flat bottom). It moves about 1 mile per hour.",
    cost: 3000,
    stock: 15,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Keep",
    description: "15 to 25 room fortified stone keep",
    cost: 150000,
    stock: 11,
    weight: -1,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Ladder, 10'",
    cost: 0.05,
    stock: 12,
    weight: 20,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lamp, Common",
    description:
      "A lamp clearly illuminates a 15-foot radius, provides shadowy illumination out to a 30-foot radius, and burns for 6 hours on a pint of oil. You can carry a lamp in one hand.",
    cost: 0.1,
    stock: 1,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lantern, Bullseye",
    description:
      "A bullseye lantern provides clear illumination in a 60-foot cone and shadowy illumination in a 120-foot cone. It burns for 6 hours on a pint of oil. You can carry a bullseye lantern in one hand.",
    cost: 12,
    stock: 16,
    weight: 3,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lantern, Hooded",
    description:
      "A hooded lantern clearly illuminates a 30-foot radius and provides shadowy illumination in a 60-foot radius. It burns for 6 hours on a pint of oil. You can carry a hooded lantern in one hand.",
    cost: 7,
    stock: 6,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lock, average",
    description: "Open Locks DC 25",
    cost: 40,
    stock: 12,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lock, good",
    description: "Open Locks DC 30",
    cost: 80,
    stock: 1,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lock, simple",
    description: "Open Locks DC 20",
    cost: 20,
    stock: 16,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Lock, superior",
    description: "Open Locks DC 40",
    cost: 150,
    stock: 10,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Longship",
    description:
      "This 75-foot-long ship with forty oars requires a total crew of 50. It has a single mast and a square sail, and it can carry 50 tons of cargo or 120 soldiers. A longship can make sea voyages. It moves about 3 miles per hour when being rowed or under sail.",
    cost: 10000,
    stock: 9,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Magnifying Glass",
    description:
      "This simple lens allows a closer look at small objects. It is also useful as a substitute for flint and steel when starting fires. Lighting a fire with a magnifying glass requires light as bright as sunlight to focus, tinder to ignite, and at least a full-round action. A magnifying glass grants a +2 circumstance bonus on Appraise checks involving any item that is small or highly detailed.",
    cost: 100,
    stock: 4,
    weight: 0,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Manacles",
    description: "Hard 10, 10 HP. Escape Artist DC 30 or burst DC 26",
    cost: 15,
    stock: 2,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Manacles, Masterwork",
    description: "Hard 10, 10 HP. Escape Artist DC 35 or burst DC 28",
    cost: 50,
    stock: 16,
    weight: 2,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Mansion",
    description:
      "10 to 20 room, 2 to 3 story mansion of wood and brick with a slate roof",
    cost: 100000,
    stock: 19,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Map Case",
    cost: 1,
    stock: 15,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Mask Filter Refill",
    cost: -1,
    stock: 10,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Mirror, Small Steel",
    cost: 1,
    stock: 10,
    weight: 0.5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Moat and Bridge",
    description: "Moat 15' deep and 30' wide with a retractable wooden bridge",
    cost: 50000,
    stock: 12,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Mobile Brace",
    cost: -1,
    stock: 18,
    weight: 3,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Monk's Outfit",
    description:
      "This simple outfit includes sandals, loose breeches, and a loose shirt, and is all bound together with sashes. The outfit is designed to give you maximum mobility, and it's made of high-quality fabric. You can hide small weapons in pockets hidden in the folds, and the sashes are strong enough to serve as short ropes.",
    cost: 5,
    stock: 19,
    weight: 2,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Mug/Tankard, clay",
    cost: 0.02,
    stock: 8,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Mule",
    description:
      "Donkeys and mules are stolid in the face of danger, hardy, surefooted, and capable of carrying heavy loads over vast distances. Unlike a horse, a donkey or a mule is willing (though not eager) to enter dungeons and other strange or threatening places.",
    cost: 8,
    stock: 9,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Musical Instrument, Common",
    cost: 5,
    stock: 7,
    weight: 3,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Musical Instrument, Masterwork",
    description:
      "A masterwork instrument grants a +2 circumstance bonus on Perform checks involving its use.",
    cost: 100,
    stock: 14,
    weight: 3,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Noble's Outfit",
    description:
      "This set of clothes is designed specifically to be expensive and to show it. Precious metals and gems are worked into the clothing. To fit into the noble crowd, every would-be noble also needs a signet ring (see Adventuring Gear, above) and jewelry (worth at least 100 gp).",
    cost: 75,
    stock: 5,
    weight: 10,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Oar",
    cost: 2,
    stock: 8,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Oil",
    description:
      "A pint of oil burns for 6 hours in a lantern. You can use a flask of oil as a splash weapon. Use the rules for alchemist's fire, except that it takes a full round action to prepare a flask with a fuse. Once it is thrown, there is a 50% chance of the flask igniting successfully.\n\nYou can pour a pint of oil on the ground to cover an area 5 feet square, provided that the surface is smooth. If lit, the oil burns for 2 rounds and deals 1d3 points of fire damage to each creature in the area.",
    cost: 0.1,
    stock: 7,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Old men's bones set",
    cost: 0.2,
    stock: 16,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Paper (sheet)",
    cost: 0.4,
    stock: 19,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Parchment (sheet)",
    cost: 0.2,
    stock: 12,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Peasant's Outfit",
    description:
      "This set of clothes consists of a loose shirt and baggy breeches, or a loose shirt and skirt or overdress. Cloth wrappings are used for shoes.",
    cost: 0.1,
    stock: 11,
    weight: 2,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Phantom Ink (Firelight)",
    description: "Fades after 1 hour",
    cost: 10,
    stock: 13,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Phantom Ink (Magical Light)",
    description: "Fades after 1 hour",
    cost: 10,
    stock: 15,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Phantom Ink (Moonlight)",
    description: "Fades after 1 hour",
    cost: 10,
    stock: 19,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Phantom Ink (Starlight)",
    description: "Fades after 1 hour",
    cost: 10,
    stock: 10,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Pick, miner's",
    cost: 3,
    stock: 7,
    weight: 10,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Pipes",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 18,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Pitcher, clay",
    cost: 0.02,
    stock: 14,
    weight: 5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Piton",
    cost: 0.1,
    stock: 15,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Pole, 10'",
    cost: 0.2,
    stock: 17,
    weight: 8,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Pony",
    cost: 30,
    stock: 2,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Portable Writing Desk",
    cost: 30,
    stock: 3,
    weight: 8,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Pot, Iron",
    cost: 0.5,
    stock: 7,
    weight: 10,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Potion",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 16,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Potion Belt",
    description: "Holds 6 potions. Free action to retrieve.",
    cost: 1,
    stock: 16,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Potion Belt, Masterwork",
    description: "Holds 10 potions. Free action to retrieve.",
    cost: 60,
    stock: 18,
    weight: 1,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Pouch, Belt",
    description: "Holds 1/5 cu ft",
    cost: 1,
    stock: 0,
    weight: 3,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Powderhorn",
    description: "Holds 2 lbs. of smokepowder.",
    cost: 55,
    stock: 12,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Powder Keg",
    description: "Holds 15 lbs. of smokepowder.",
    cost: 400,
    stock: 16,
    weight: 20,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Prayer Book",
    cost: 10,
    stock: 9,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Prayer Book, Compact",
    cost: 15,
    stock: 1,
    weight: 1,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Ram, portable",
    description:
      "This iron-shod wooden beam gives you a +2 circumstance bonus on Strength checks made to break open a door and it allows a second person to help you without having to roll, increasing your bonus by 2.",
    cost: 10,
    stock: 18,
    weight: 20,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Rations, Trail (per day)",
    cost: 0.5,
    stock: 9,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Reading Lamp",
    cost: 15,
    stock: 14,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Ring",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 12,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Robe",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 4,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Rod",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 5,
    weight: 5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Rope Climber",
    cost: -1,
    stock: 5,
    weight: 3,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Rope, Hempen",
    description:
      "This rope has 2 hit points and can be burst with a DC 23 Strength check.",
    cost: 1,
    stock: 15,
    weight: 10,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Rope, Silk",
    description:
      "This rope has 4 hit points and can be burst with a DC 24 Strength check. It is so supple that it provides a +2 circumstance bonus on Use Rope checks.",
    cost: 10,
    stock: 9,
    weight: 5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Rowboat",
    description:
      "This 8- to 12-foot-long boat holds two or three Medium passengers. It moves about 1-1/2 miles per hour.",
    cost: 50,
    stock: 4,
    weight: -1,
    image_link: "/img/transport.port",
    image_alt_text: "Transport",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Royal Outfit",
    description:
      "This is just the clothing, not the royal scepter, crown, ring, and other accoutrements. Royal clothes are ostentatious, with gems, gold, silk, and fur in abundance.",
    cost: 200,
    stock: 10,
    weight: 15,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Sack",
    description: "Holds 1 cu ft",
    cost: 0.1,
    stock: 8,
    weight: 0.5,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Saddle, Exotic Military",
    description:
      "An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles.",
    cost: 60,
    stock: 9,
    weight: 40,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddle, Exotic Pack",
    description:
      "An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles.",
    cost: 15,
    stock: 7,
    weight: 20,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddle, Exotic Riding",
    description:
      "An exotic saddle is like a normal saddle of the same sort except that it is designed for an unusual mount. Exotic saddles come in military, pack, and riding styles.",
    cost: 30,
    stock: 15,
    weight: 30,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddle, Military",
    description:
      "A military saddle braces the rider, providing a +2 circumstance bonus on Ride checks related to staying in the saddle. If you're knocked unconscious while in a military saddle, you have a 75% chance to stay in the saddle (compared to 50% for a riding saddle).",
    cost: 20,
    stock: 0,
    weight: 30,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddle, Pack",
    description:
      "A pack saddle holds gear and supplies, but not a rider. It holds as much gear as the mount can carry.",
    cost: 5,
    stock: 2,
    weight: 15,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddle, Riding",
    description: "The standard riding saddle supports a rider.",
    cost: 10,
    stock: 4,
    weight: 25,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddlebags",
    cost: 4,
    stock: 17,
    weight: 8,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Saddlebags",
    cost: 8,
    stock: 12,
    weight: 4,
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Sailing Ship",
    description:
      "This larger, seaworthy ship is 75 to 90 feet long and 20 feet wide and has a crew of 20. It can carry 150 tons of cargo. It has square sails on its two masts and can make sea voyages. It moves about 2 miles per hour.",
    cost: 10000,
    stock: 0,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Scale, Merchant's",
    description:
      "A scale grants a +2 circumstance bonus on Appraise checks involving items that are valued by weight, including anything made of precious metals.",
    cost: 2,
    stock: 0,
    weight: 1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Scent-Breaker",
    description: "Herbs break scent trail",
    cost: 5,
    stock: 12,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Scholar's Outfit",
    description:
      "Perfect for a scholar, this outfit includes a robe, a belt, a cap, soft shoes, and possibly a cloak.",
    cost: 5,
    stock: 4,
    weight: 6,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Scripture",
    cost: 10,
    stock: 19,
    weight: 3,
    image_link: "/img/scroll.png",
    image_alt_text: "Scroll",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Scripture, Compact",
    cost: 15,
    stock: 19,
    weight: 1,
    image_link: "/img/scroll.png",
    image_alt_text: "Scroll",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Scroll",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 14,
    weight: 0,
    image_link: "/img/scroll.png",
    image_alt_text: "Scroll",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Scroll Organizer",
    description: "Fifteen 'pockets' for scrolls",
    cost: 5,
    stock: 17,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Sealing Wax",
    cost: 1,
    stock: 5,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Secret component compartment",
    description: "Hold components for one spell",
    cost: 15,
    stock: 3,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Secret component pocket",
    description: "Hold components for one spell",
    cost: 5,
    stock: 5,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Sewing Needle",
    cost: 0.5,
    stock: 5,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Signal Whistle",
    cost: 0.8,
    stock: 16,
    weight: 0.1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Signet Ring",
    cost: 5,
    stock: 8,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Simple House",
    description: "1 to 3 room wooden house with thatch roof",
    cost: 1000,
    stock: 9,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Sled",
    description:
      "This is a wagon on runners for moving through snow and over ice. In general, two horses (or other beasts of burden) draw it. A sled comes with the harness needed to pull it.",
    cost: 20,
    stock: 0,
    weight: 300,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Sledge",
    cost: 1,
    stock: 17,
    weight: 10,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Smoke Stick",
    description:
      "This alchemically treated wooden stick instantly creates thick, opaque smoke when ignited. The smoke fills a 10- foot cube (treat the effect as a fog cloud spell, except that a moderate or stronger wind dissipates the smoke in 1 round). The stick is consumed after 1 round, and the smoke dissipates naturally.",
    cost: 20,
    stock: 9,
    weight: 0.5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Snuffing Bell",
    cost: 6,
    stock: 5,
    weight: 4,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Soap (lb.)",
    cost: 0.5,
    stock: 11,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Songbook, Bard's",
    cost: 15,
    stock: 11,
    weight: 3,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Spade or Shovel",
    cost: 2,
    stock: 0,
    weight: 8,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Spell Component Pouch",
    description:
      "A spellcaster with a spell component pouch is assumed to have all the material components and focuses needed for spellcasting, except for those components that have a specific cost, divine focuses, and focuses that wouldn't fit in a pouch.",
    cost: 5,
    stock: 6,
    weight: 3,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Spellbook, Wizard's (blank)",
    description:
      "A spellbook has 100 pages of parchment, and each spell takes up one page per spell level (one page each for 0-level spells).",
    cost: 15,
    stock: 12,
    weight: 3,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Spyglass",
    description:
      "Objects viewed through a spyglass are magnified to twice their size.",
    cost: 1000,
    stock: 13,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Staff",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 10,
    weight: 5,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Sunrod",
    description:
      "This 1-foot-long, gold-tipped, iron rod glows brightly when struck. It clearly illuminates a 30-foot radius and provides shadowy illumination in a 60-foot radius. It glows for 6 hours, after which the gold tip is burned out and worthless.",
    cost: 2,
    stock: 6,
    weight: 1,
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Sure-grip",
    cost: 20,
    stock: 6,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Talis Deck",
    cost: 2,
    stock: 3,
    weight: 0.25,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Tanglefoot Bag",
    description:
      "When you throw a tanglefoot bag at a creature (as a ranged touch attack with a range increment of 10 feet), the bag comes apart and the goo bursts out, entangling the target and then becoming tough and resilient upon exposure to air. An entangled creature takes a -2 penalty on attack rolls and a -4 penalty to Dexterity and must make a DC 15 Reflex save or be glued to the floor, unable to move. Even on a successful save, it can move only at half speed. Huge or larger creatures are unaffected by a tanglefoot bag. A flying creature is not stuck to the floor, but it must make a DC 15 Reflex save or be unable to fly (assuming it uses its wings to fly) and fall to the ground. A tanglefoot bag does not function underwater.\n\nA creature that is glued to the floor (or unable to fly) can break free by making a DC 17 Strength check or by dealing 15 points of damage to the goo with a slashing weapon. A creature trying to scrape goo off itself, or another creature assisting, does not need to make an attack roll; hitting the goo is automatic, after which the creature that hit makes a damage roll to see how much of the goo was scraped off. Once free, the creature can move (including flying) at half speed. A character capable of spellcasting who is bound by the goo must make a DC 15 Concentration check to cast a spell. The goo becomes brittle and fragile after 2d4 rounds, cracking apart and losing its effectiveness. An application of universal solvent to a stuck creature dissolves the alchemical goo immediately.",
    cost: 50,
    stock: 19,
    weight: 4,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Tent",
    cost: 1,
    stock: 2,
    weight: 20,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Thieves' Tools",
    description:
      "This kit contains the tools you need to use the Disable Device and Open Lock skills. Without these tools, you must improvise tools, and you take a -2 circumstance penalty on Disable Device and Open Locks checks.",
    cost: 3,
    stock: 15,
    weight: 1,
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Thieves' Tools, Masterwork",
    description:
      "This kit contains extra tools and tools of better make, which grant a +2 circumstance bonus on Disable Device and Open Lock checks.",
    cost: 1,
    stock: 12,
    weight: 2,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Thunderstone",
    description:
      "You can throw this stone as a ranged attack with a range increment of 20 feet. When it strikes a hard surface (or is struck hard), it creates a deafening bang that is treated as a sonic attack. Each creature within a 10-foot-radius spread must make a DC 15 Fortitude save or be deafened for 1 hour. A deafened creature, in addition to the obvious effects, takes a -4 penalty on initiative and has a 20% chance to miscast and lose any spell with a verbal component that it tries to cast.\n\nSince you don't need to hit a specific target, you can simply aim at a particular 5-foot square. Treat the target square as AC 5.",
    cost: 30,
    stock: 16,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Tindertwig",
    description:
      "The alchemical substance on the end of this small, wooden stick ignites when struck against a rough surface. Creating a flame with a tindertwig is much faster than creating a flame with flint and steel (or a magnifying glass) and tinder. Lighting a torch with a tindertwig is a standard action (rather than a full-round action), and lighting any other fire with one is at least a standard action.",
    cost: 1,
    stock: 17,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Tool, Masterwork",
    description:
      "This well-made item is the perfect tool for the job. It grants a +2 circumstance bonus on a related skill check (if any). Bonuses provided by multiple masterwork items used toward the same skill check do not stack.",
    cost: -1,
    stock: 1,
    weight: -1,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Torch",
    description:
      "A torch burns for 1 hour, clearly illuminating a 20-foot radius and providing shadowy illumination out to a 40- foot radius. If a torch is used in combat, treat it as a one-handed improvised weapon that deals bludgeoning damage equal to that of a gauntlet of its size, plus 1 point of fire damage.",
    cost: 0.01,
    stock: 2,
    weight: 1,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Torch, Ever-Burning",
    description:
      "This otherwise normal torch has a continual flame spell cast upon it. An ever-burning torch clearly illuminates a 20-foot radius and provides shadowy illumination out to a 40-foot radius.",
    cost: -1,
    stock: 3,
    weight: -1,

    image_link: "/img/specialitems.png",
    image_alt_text: "Special Substances",
    category_id: 3,
    additional_information: { type: "Special Substances & Items" },
  },
  {
    product_name: "Tower",
    description: "3 level, round or square stone tower",
    cost: 50000,
    stock: 19,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Traveler's Outfit",
    description:
      "This set of clothes consists of boots, a wool skirt or breeches, a sturdy belt, a shirt (perhaps with a vest or jacket), and an ample cloak with a hood.",
    cost: 1,
    stock: 17,
    weight: 5,
    image_link: "/img/clothing.png",
    image_alt_text: "Clothing",
    category_id: 3,
    additional_information: { type: "Clothing" },
  },
  {
    product_name: "Vial",
    description:
      "A vial holds 1 ounce of liquid. The stoppered container usually is no more than 1 inch wide and 3 inches high.",
    cost: 1,
    stock: 0,
    weight: 0,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Wagon",
    description:
      "This is a four-wheeled, open vehicle for transporting heavy loads. In general, two horses (or other beasts of burden) draw it. A wagon comes with the harness needed to pull it.",
    cost: 35,
    stock: 10,
    weight: 400,
    image_link: "/img/transport.port",
    image_alt_text: "Transport",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Wand",
    description: "(Usually a magical item)",
    cost: 0,
    stock: 19,
    weight: 0,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: {},
  },
  {
    product_name: "Warhorse, heavy",
    cost: 400,
    stock: 8,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Warhorse, light",
    cost: 150,
    stock: 0,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "War Pony",
    cost: 100,
    stock: 19,
    weight: -1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Mounts & Related Gear" },
  },
  {
    product_name: "Warship",
    description:
      "This 100-foot-long ship has a single mast, although oars can also propel it. It has a crew of 60 to 80 rowers. This ship can carry 160 soldiers, but not for long distances, since there isn't room for supplies to support that many people. The warship cannot make sea voyages and sticks to the coast. It is not used for cargo. It moves about 2-1/2 miles per hour when being rowed or under sail.",
    cost: 25000,
    stock: 10,
    weight: -1,
    image_link: "/img/castle.png",
    image_alt_text: "Castle",
    category_id: 3,
    additional_information: { type: "Transport" },
  },
  {
    product_name: "Water Clock",
    description:
      "This large, bulky contrivance gives the time accurate to within half an hour per day since it was last set. It requires a source of water, and it must be kept still because it marks time by the regulated flow of droplets of water.",
    cost: 1000,
    stock: 14,
    weight: 200,
    image_link: "/img/tools&skillsKit.png",
    image_alt_text: "Tools & Skills Kit",
    category_id: 3,
    additional_information: { type: "Tools & Skill Kits" },
  },
  {
    product_name: "Waterskin",
    description: "Holds 1/2 gallon of liquid",
    cost: 1,
    stock: 14,
    weight: 4,
    image_link: "/img/adventuringGear.png",
    image_alt_text: "Adventuring Gear",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
  {
    product_name: "Whetstone",
    cost: 0.2,
    stock: 14,
    weight: 1,
    image_link: "/img/specialitems.png",
    image_alt_text: "Special Items",
    category_id: 3,
    additional_information: { type: "Adventuring Gear" },
  },
];

const seedGear = () => Product.bulkCreate(gearData);

module.exports = seedGear;
